(package "noflet"
         "0.0.15"
         "locally override functions")

(website-url "https://github.com/elp-revive/noflet")
(keywords "lisp")

(package-file "noflet.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
